-- MySQL Script generated by MySQL Workbench
-- Thu Jun 11 23:10:08 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tkpm_quanlynhasach
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tkpm_quanlynhasach` ;

-- -----------------------------------------------------
-- Schema tkpm_quanlynhasach
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tkpm_quanlynhasach` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `tkpm_quanlynhasach` ;

-- -----------------------------------------------------
-- Table `tkpm_quanlynhasach`.`company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tkpm_quanlynhasach`.`company` ;

CREATE TABLE IF NOT EXISTS `tkpm_quanlynhasach`.`company` (
  `idCompany` INT(11) NOT NULL,
  `nameCompany` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idCompany`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tkpm_quanlynhasach`.`store`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tkpm_quanlynhasach`.`store` ;

CREATE TABLE IF NOT EXISTS `tkpm_quanlynhasach`.`store` (
  `idstore` INT(11) NOT NULL AUTO_INCREMENT,
  `addressStore` VARCHAR(45) NOT NULL,
  `revenueStore` INT(11) NULL DEFAULT NULL,
  `outcomeStore` INT(11) NULL DEFAULT NULL,
  `company_idCompany` INT(11) NOT NULL,
  PRIMARY KEY (`idstore`, `company_idCompany`),
  UNIQUE INDEX `idstore_UNIQUE` (`idstore` ASC) VISIBLE,
  INDEX `fk_store_company_idx` (`company_idCompany` ASC) VISIBLE,
  CONSTRAINT `fk_store_company`
    FOREIGN KEY (`company_idCompany`)
    REFERENCES `tkpm_quanlynhasach`.`company` (`idCompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tkpm_quanlynhasach`.`bill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tkpm_quanlynhasach`.`bill` ;

CREATE TABLE IF NOT EXISTS `tkpm_quanlynhasach`.`bill` (
  `idBill` INT(11) NOT NULL AUTO_INCREMENT,
  `totalBill` INT(11) NOT NULL,
  `dateBill` DATE NULL DEFAULT NULL,
  `madeBill` INT(11) NULL DEFAULT NULL COMMENT 'id employee',
  `noteBill` VARCHAR(200) NULL DEFAULT NULL,
  `store_idstore` INT(11) NOT NULL,
  PRIMARY KEY (`idBill`, `store_idstore`),
  INDEX `fk_bill_store1_idx` (`store_idstore` ASC) VISIBLE,
  CONSTRAINT `fk_bill_store1`
    FOREIGN KEY (`store_idstore`)
    REFERENCES `tkpm_quanlynhasach`.`store` (`idstore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tkpm_quanlynhasach`.`item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tkpm_quanlynhasach`.`item` ;

CREATE TABLE IF NOT EXISTS `tkpm_quanlynhasach`.`item` (
  `idItem` INT(11) NOT NULL AUTO_INCREMENT,
  `nameItem` VARCHAR(45) NOT NULL,
  `priceItem` INT(11) NOT NULL,
  PRIMARY KEY (`idItem`),
  UNIQUE INDEX `idItems_UNIQUE` (`idItem` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tkpm_quanlynhasach`.`book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tkpm_quanlynhasach`.`book` ;

CREATE TABLE IF NOT EXISTS `tkpm_quanlynhasach`.`book` (
  `idbook` INT(11) NOT NULL AUTO_INCREMENT,
  `authorBook` VARCHAR(45) NULL DEFAULT NULL,
  `descriptionBook` VARCHAR(45) NULL DEFAULT NULL,
  `pulisherBook` VARCHAR(45) NULL DEFAULT NULL,
  `yearBook` YEAR(4) NULL DEFAULT NULL,
  `item_idItem` INT(11) NOT NULL,
  PRIMARY KEY (`idbook`, `item_idItem`),
  INDEX `fk_book_item1_idx` (`item_idItem` ASC) VISIBLE,
  CONSTRAINT `fk_book_item1`
    FOREIGN KEY (`item_idItem`)
    REFERENCES `tkpm_quanlynhasach`.`item` (`idItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tkpm_quanlynhasach`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tkpm_quanlynhasach`.`customer` ;

CREATE TABLE IF NOT EXISTS `tkpm_quanlynhasach`.`customer` (
  `idcustomer` INT(11) NOT NULL AUTO_INCREMENT,
  `nameCustomer` VARCHAR(45) NULL DEFAULT NULL,
  `phoneCustomer` VARCHAR(10) NOT NULL,
  `dobCustomer` DATE NULL DEFAULT NULL,
  `emailCustomer` VARCHAR(45) NULL DEFAULT NULL,
  `identifyIDCustomer` VARCHAR(45) NULL DEFAULT NULL,
  `store_idstore` INT(11) NOT NULL,
  PRIMARY KEY (`idcustomer`, `store_idstore`),
  UNIQUE INDEX `idcustomer_UNIQUE` (`idcustomer` ASC) VISIBLE,
  INDEX `fk_customer_store1_idx` (`store_idstore` ASC) VISIBLE,
  CONSTRAINT `fk_customer_store1`
    FOREIGN KEY (`store_idstore`)
    REFERENCES `tkpm_quanlynhasach`.`store` (`idstore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tkpm_quanlynhasach`.`discount`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tkpm_quanlynhasach`.`discount` ;

CREATE TABLE IF NOT EXISTS `tkpm_quanlynhasach`.`discount` (
  `idDiscount` INT(11) NOT NULL AUTO_INCREMENT,
  `startDate` DATE NOT NULL,
  `endDate` DATE NOT NULL,
  `discount` INT(11) NOT NULL,
  `store_idstore` INT(11) NOT NULL,
  PRIMARY KEY (`idDiscount`, `store_idstore`),
  INDEX `fk_discount_store1_idx` (`store_idstore` ASC) VISIBLE,
  CONSTRAINT `fk_discount_store1`
    FOREIGN KEY (`store_idstore`)
    REFERENCES `tkpm_quanlynhasach`.`store` (`idstore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tkpm_quanlynhasach`.`storage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tkpm_quanlynhasach`.`storage` ;

CREATE TABLE IF NOT EXISTS `tkpm_quanlynhasach`.`storage` (
  `idstorage` INT(11) NOT NULL,
  `addressStorage` VARCHAR(45) NOT NULL,
  `company_idCompany` INT(11) NOT NULL,
  PRIMARY KEY (`idstorage`, `company_idCompany`),
  INDEX `fk_storage_company1_idx` (`company_idCompany` ASC) VISIBLE,
  CONSTRAINT `fk_storage_company1`
    FOREIGN KEY (`company_idCompany`)
    REFERENCES `tkpm_quanlynhasach`.`company` (`idCompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tkpm_quanlynhasach`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tkpm_quanlynhasach`.`employee` ;

CREATE TABLE IF NOT EXISTS `tkpm_quanlynhasach`.`employee` (
  `idEmployee` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `passwordEmployee` VARCHAR(45) NOT NULL,
  `nameEmployee` VARCHAR(45) NOT NULL,
  `phoneEmployee` VARCHAR(10) NOT NULL,
  `addressEmployee` VARCHAR(45) NULL DEFAULT NULL,
  `startDateEmployee` DATE NOT NULL,
  `salaryEmployee` INT(10) UNSIGNED ZEROFILL NULL DEFAULT NULL,
  `statusEmployee` INT(11) NOT NULL DEFAULT '1' COMMENT '0: not working\\n1: working\\n2: diffrent',
  `positionEmployee` INT(11) NOT NULL DEFAULT '0' COMMENT '0: normal employee\\n1: manager\\n2: director',
  `store_idstore` INT(11) NULL,
  `storage_idstorage` INT(11) NULL,
  PRIMARY KEY (`idEmployee`),
  UNIQUE INDEX `idEmployee_UNIQUE` (`idEmployee` ASC) VISIBLE,
  INDEX `fk_employee_store1_idx` (`store_idstore` ASC) VISIBLE,
  INDEX `fk_employee_storage1_idx` (`storage_idstorage` ASC) VISIBLE,
  CONSTRAINT `fk_employee_store1`
    FOREIGN KEY (`store_idstore`)
    REFERENCES `tkpm_quanlynhasach`.`store` (`idstore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_storage1`
    FOREIGN KEY (`storage_idstorage`)
    REFERENCES `tkpm_quanlynhasach`.`storage` (`idstorage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tkpm_quanlynhasach`.`genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tkpm_quanlynhasach`.`genre` ;

CREATE TABLE IF NOT EXISTS `tkpm_quanlynhasach`.`genre` (
  `idGenre` INT(11) NOT NULL AUTO_INCREMENT,
  `nameGenre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idGenre`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tkpm_quanlynhasach`.`book_has_genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tkpm_quanlynhasach`.`book_has_genre` ;

CREATE TABLE IF NOT EXISTS `tkpm_quanlynhasach`.`book_has_genre` (
  `book_idbook` INT(11) NOT NULL,
  `genre_idGenre` INT(11) NOT NULL,
  PRIMARY KEY (`book_idbook`, `genre_idGenre`),
  INDEX `fk_book_has_genre_genre1_idx` (`genre_idGenre` ASC) VISIBLE,
  INDEX `fk_book_has_genre_book1_idx` (`book_idbook` ASC) VISIBLE,
  CONSTRAINT `fk_book_has_genre_book1`
    FOREIGN KEY (`book_idbook`)
    REFERENCES `tkpm_quanlynhasach`.`book` (`idbook`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_book_has_genre_genre1`
    FOREIGN KEY (`genre_idGenre`)
    REFERENCES `tkpm_quanlynhasach`.`genre` (`idGenre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tkpm_quanlynhasach`.`storage_has_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tkpm_quanlynhasach`.`storage_has_item` ;

CREATE TABLE IF NOT EXISTS `tkpm_quanlynhasach`.`storage_has_item` (
  `storage_idstorage` INT(11) NOT NULL,
  `item_idItem` INT(11) NOT NULL,
  `countItem` INT NULL DEFAULT 0,
  PRIMARY KEY (`storage_idstorage`, `item_idItem`),
  INDEX `fk_storage_has_item_item1_idx` (`item_idItem` ASC) VISIBLE,
  INDEX `fk_storage_has_item_storage1_idx` (`storage_idstorage` ASC) VISIBLE,
  CONSTRAINT `fk_storage_has_item_storage1`
    FOREIGN KEY (`storage_idstorage`)
    REFERENCES `tkpm_quanlynhasach`.`storage` (`idstorage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_storage_has_item_item1`
    FOREIGN KEY (`item_idItem`)
    REFERENCES `tkpm_quanlynhasach`.`item` (`idItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tkpm_quanlynhasach`.`store_has_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tkpm_quanlynhasach`.`store_has_item` ;

CREATE TABLE IF NOT EXISTS `tkpm_quanlynhasach`.`store_has_item` (
  `store_idstore` INT(11) NOT NULL,
  `item_idItem` INT(11) NOT NULL,
  PRIMARY KEY (`store_idstore`, `item_idItem`),
  INDEX `fk_store_has_item_item1_idx` (`item_idItem` ASC) VISIBLE,
  INDEX `fk_store_has_item_store1_idx` (`store_idstore` ASC) VISIBLE,
  CONSTRAINT `fk_store_has_item_store1`
    FOREIGN KEY (`store_idstore`)
    REFERENCES `tkpm_quanlynhasach`.`store` (`idstore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_store_has_item_item1`
    FOREIGN KEY (`item_idItem`)
    REFERENCES `tkpm_quanlynhasach`.`item` (`idItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
